import { Participant } from '@/types/calendar';

export const PARTICIPANTS: Participant[] = [
  { id: 1, name: 'John Doe', email: 'john@example.com', departmentId: 1 },
  { id: 2, name: 'Jane Smith', email: 'jane@example.com', departmentId: 1 },
  { id: 3, name: 'Bob Wilson', email: 'bob@example.com', departmentId: 1 },
  { id: 4, name: 'Alice Brown', email: 'alice@example.com', departmentId: 1 },
  {
    id: 5,
    name: 'Michael Johnson',
    email: 'michael@example.com',
    departmentId: 2,
  },
  { id: 6, name: 'Emily Davis', email: 'emily@example.com', departmentId: 3 },
  { id: 7, name: 'David Miller', email: 'david@example.com', departmentId: 4 },
  { id: 8, name: 'Sarah Wilson', email: 'sarah@example.com', departmentId: 5 },
  { id: 9, name: 'James Taylor', email: 'james@example.com', departmentId: 1 },
  { id: 10, name: 'Emma Anderson', email: 'emma@example.com', departmentId: 2 },
  {
    id: 11,
    name: 'William Thomas',
    email: 'william@example.com',
    departmentId: 3,
  },
  {
    id: 12,
    name: 'Olivia Martinez',
    email: 'olivia@example.com',
    departmentId: 4,
  },
  {
    id: 13,
    name: 'Daniel White',
    email: 'daniel@example.com',
    departmentId: 5,
  },
  { id: 14, name: 'Sofia Garcia', email: 'sofia@example.com', departmentId: 1 },
  {
    id: 15,
    name: 'Matthew Lee',
    email: 'matthew@example.com',
    departmentId: 2,
  },
  {
    id: 16,
    name: 'Isabella Clark',
    email: 'isabella@example.com',
    departmentId: 3,
  },
  {
    id: 17,
    name: 'Joseph Rodriguez',
    email: 'joseph@example.com',
    departmentId: 4,
  },
  {
    id: 18,
    name: 'Charlotte Lewis',
    email: 'charlotte@example.com',
    departmentId: 5,
  },
  { id: 19, name: 'Henry Walker', email: 'henry@example.com', departmentId: 1 },
  {
    id: 20,
    name: 'Victoria Hall',
    email: 'victoria@example.com',
    departmentId: 2,
  },
  {
    id: 21,
    name: 'Benjamin King',
    email: 'benjamin@example.com',
    departmentId: 3,
  },
  { id: 22, name: 'Mia Wright', email: 'mia@example.com', departmentId: 4 },
  {
    id: 23,
    name: 'Alexander Hill',
    email: 'alexander@example.com',
    departmentId: 5,
  },
  { id: 24, name: 'Ava Scott', email: 'ava@example.com', departmentId: 1 },
  {
    id: 25,
    name: 'Christopher Green',
    email: 'christopher@example.com',
    departmentId: 2,
  },
  {
    id: 26,
    name: 'Sophia Baker',
    email: 'sophia@example.com',
    departmentId: 3,
  },
  {
    id: 27,
    name: 'Andrew Adams',
    email: 'andrew@example.com',
    departmentId: 4,
  },
  {
    id: 28,
    name: 'Elizabeth Nelson',
    email: 'elizabeth@example.com',
    departmentId: 5,
  },
  { id: 29, name: 'Ryan Carter', email: 'ryan@example.com', departmentId: 1 },
  { id: 30, name: 'Grace Morgan', email: 'grace@example.com', departmentId: 2 },
  {
    id: 31,
    name: 'Lucas Phillips',
    email: 'lucas@example.com',
    departmentId: 3,
  },
  { id: 32, name: 'Chloe Turner', email: 'chloe@example.com', departmentId: 4 },
  {
    id: 33,
    name: 'Nathan Cooper',
    email: 'nathan@example.com',
    departmentId: 5,
  },
  { id: 34, name: 'Zoe Parker', email: 'zoe@example.com', departmentId: 1 },
];
